language: node_js
node_js:
- "node"

cache: yarn
branches:
  only:
  - master

script:
- yarn run build
- yarn run lint:js
- yarn run lint:css
- yarn test

before_deploy: yarn run build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: build
  on:
    branch: master
